project:
  type: book
  output-dir: docs

book:
  title: "Transdiagnosic Addiction Laboratory Manual"
  author: "TALab Team"
  date: "2024-02-29" # Don't forget to update the date when publishing changes
  chapters:
    - part: index.qmd
      chapters:
        - mission.qmd
    - part: starting.qmd
      chapters:
        - volunteer.qmd
        - undergrad.qmd
        - graduate.qmd
    - part: policies.qmd
      chapters:
        - philosophy.qmd
        - rules.qmd
        - funding.qmd
        - lab.qmd
        - resources.qmd
    - part: setup.qmd
      chapters:
        - initializing.qmd
        - management.qmd
        - analysis.qmd
    - part: clinical.qmd
      chapters:
        - comps.qmd
        - practica.qmd
        - guidelines.qmd
        - residency.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

