---
title: "Analyses & Related Resources"
---

For statistical analyses, Igor strongly recommends that students learn R and conduct analyses using R. However, exceptions may be made on a case-by-case basis. For resources on R usage, consult [this chapter](resources.qmd). Below, you can find a variety of resources which you may need throughout the course of your program.

Any resources missing? Please email {{< var names.manager >}} to have them added to the list.

+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Learning Statistics with R](https://learningstatisticswithr.com/book/)                  | General resource for getting started with analyses in R. Specifically geared towards Psychology students.                                                                                                              |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Moderated mediation](https://doi.org/10.1080/00273170701341316)                         | How-to and sample size guide                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Handling missing data](https://www.theanalysisfactor.com/missing-data-mechanism/)       | Including Little's MCAR and diagnosing                                                                                                                                                                                 |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Effect size calculators                                                                  | [This website](https://www.socscistatistics.com/effectsize/default3.aspx) for Chi-square/T-tests.                                                                                                                      |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Bootstrapping                                                                            | [This website](https://statisticsbyjim.com/hypothesis-testing/bootstrapping/) for an explanation of what bootstrapping is and use cases.                                                                               |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Power analyses / sample size calculators                                                 | This resource [for SEM](https://www.danielsoper.com/statcalc/calculator.aspx?id=89). Also consider using [GPower](https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower). |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Handling outliers](•	https://www.theanalysisfactor.com/outliers-to-drop-or-not-to-drop/) | Descriptions of the different means to handle outliers and when you should use them.                                                                                                                                   |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Directed Acyclical Graphs (DAGs)](https://www.dagitty.net/)                             | Website for creating your own DAGs.                                                                                                                                                                                    |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Content/thematic analysis                                                                | Below, you will find a variety of resources specific to content/thematic analysis.                                                                                                                                     |
|                                                                                          |                                                                                                                                                                                                                        |
|                                                                                          | -   [Understanding data saturation](https://doi.org/10.1371/journal.pone.0232076)                                                                                                                                      |
|                                                                                          |                                                                                                                                                                                                                        |
|                                                                                          | -   [Description of thematic analysis](https://writing.colostate.edu/guides/guide.cfm?guideid=61)                                                                                                                      |
|                                                                                          |                                                                                                                                                                                                                        |
|                                                                                          | -   2 gold standard papers to follow along for the coding process ([1](http://dx.doi.org/10.3402/qhw.v9.26152), [2](https://doi.org/10.1191/1478088706qp063oa))                                                        |
|                                                                                          |                                                                                                                                                                                                                        |
|                                                                                          | -   [Example writeup using thematic analysis](http://dx.doi.org/10.1016/j.schres.2015.12.008)                                                                                                                          |
|                                                                                          |                                                                                                                                                                                                                        |
|                                                                                          | -   [How-to guide](https://doi.org/10.7275/z6fm-2e34)                                                                                                                                                                  |
|                                                                                          |                                                                                                                                                                                                                        |
|                                                                                          | -   [Justification of sample size](https://doi.org/10.1186/s12874-018-0594-7)                                                                                                                                          |
+------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
