---
title: "Comprehensive projects"
---

Rather than a comprehensive exam, the department’s comprehensive requirement is a series of two projects completed under the supervision of different faculty members. The comprehensive plan should be developed to ensure sufficient breadth of training in psychology.

Typically, the plan will comprise two comp projects in addition to the students’ dissertation. One (of two) comps must be empirical in nature (i.e., includes all aspects of the scientific process) and the student must be involved in it from conception of idea to dissemination of results (typically first comp). Each student’s comprehensive plan is presented to and approved by the Clinical Program Committee at the (monthly) meeting. Some issues of particular relevance to students in the Clinical Program, as well as a summary of general issues relating to comprehensives, appear below. Students are also encouraged to consult the Comprehensive Guidelines for Clinical Psychology Students (Appendix C) for suggested timelines.

## The First Comprehensive

The comprehensive project that is proposed early in the winter term of the first year in the Program (PSYO 5000) is considered the First Comprehensive. Generally, this project is conducted under the supervision of the dissertation supervisor and typically involves an empirical study involving original data collection. Students entering with Master's degrees complete their first comprehensive under the same conditions. The comprehensive examining committee for the first comprehensive comprises the dissertation supervisor(s), the DCT \[or designate(s)\], and two core clinical faculty members. The role of the committee is to evaluate quality and progress.

The first-year comprehensive project, including the written components and oral presentations and defense are important milestones in the student’s completion of the degree. This project is a critical indicator of the student’s research abilities. Student’s performance throughout this process (written and oral) is evaluated by the examining committee, who determine whether they meet the required standards to continue in the program or not. Students must demonstrate a solid grasp of the theory/rationale, methods, statistics, and potential implications of their project.

A written proposal \[(APA format) including Introduction, Methods, Expected Results, and Potential Implications, not exceeding ten (10) double spaced pages (not including references)\] should be submitted to the Clinical Program administrative assistant, who will distribute to the comprehensive committee, at least two weeks prior to the presentation. This component is typically due at the end of the first term. A 2nd Reader, whose expertise is relevant to the student’s project, will also review and provide feedback, which is submitted to the committee. The reader will be at arm’s length from the student and supervisor (i.e., not a collaborator on the proposed project) and will ideally serve in this role for both the proposal and final version of the comp. The 2nd Reader is not a member of the examining committee. The Committee meets with the students in January of 1st year to help guide the process. For this meeting, an oral proposal of the comprehensive project is presented to the committee (15-minute presentation) and students answer questions about their proposal from the committee (15 minutes). All students who are presenting are expected to remain for the duration of all presentations. The committee must approve the written and the oral proposals for the student to continue with this project as their first year comprehensive.

The final version of the comprehensive project will be submitted in writing in early-May during the second year of the program. The comprehensive defense will occur approximately three weeks later. If submitting in manuscript form, the title page should be altered to indicate it is the first comp and should contain just the student’s name as author with supervisor(s) identified on a separate line. The bottom of the title page can contain the APA reference to the submitted paper as this acknowledges the contributions of the coauthors and allows the committee to see it has been submitted for publication. The comprehensive is examined orally (like a thesis defense) by the committee. The examination will usually be open to the public and will consist of a 10- minute oral presentation followed by questions. All students who are presenting are expected to remain for the duration of all presentations. The committee will recommend to the Director of Clinical Training a course of action with respect to student advancement in the Program. Following successful defense/completion of the first comprehensive, students must arrange to meet with both the dissertation supervision and comp chair together on an annual basis.

### Following completion of the first comprehensive...

Clinical students must meet jointly with their dissertation supervisor and comprehensive chair on an annual basis. One additional comprehensive project, approved by the CPC, must be completed. The remaining comprehensive is usually supervised by faculty other than the dissertation supervisor and may include up to one other dissertation committee member. The student selects the chair of the comprehensive committee, usually also the supervisor of this additional comprehensive project, who helps guide the student in the selection of comprehensives and the submission of a comprehensive plan. The plan must outline the comprehensive and the dissertation (to ensure sufficient breadth of training and to avoid too much overlap in content and/or methods) as well as the outcome for the completion of the comprehensive. The chair of the comprehensive committee is a faculty member who presents the plan for the comprehensive to the clinical faculty. The timing of this project is somewhat flexible, but it is generally advisable for students to have a plan presented for approval no later than December of Year 3.

## The second comprehensive

Best be started early in the Fall or Winter of third year of the program. Care must be taken to craft a project that is significant enough to provide a valuable learning experience and not so extensive as to be a barrier to timely completion of the degree. Students should discuss this with both the individual supervisor of the project and with the chair of the comprehensive committee. The second comprehensive project often has a more limited scope than the first comprehensive project. The outcome of the second project depends on the type of project and the stage/aspect of the scientific process the student is working on. Students are encouraged to write-up the results of their comp projects for publication, but this does not need to be the endpoint for all comprehensive projects. Several example outcomes are provided in the Comprehensive Guidelines for Clinical Psychology Students (Appendix C). Comprehensives must be separate from the dissertation. They are designed to represent a breadth of experience to develop skills and knowledge in areas unrelated to the dissertation. A listing of possible comprehensives is compiled and distributed on an annual basis. A binder with examples of approved comprehensive plans is available in the Clinical Administrative Assistant’s office. Students should refer to the Comprehensive Guidelines for Clinical Psychology Students for further details. NB: Requests for an exemption from one comprehensive project may be made from clinical students who are admitted with an empirical Master's following the successful defence of the first clinical comprehensive. All such requests will be considered on a case-by-case basis and will require the approval of the DCT and the dissertation supervisor.
