# Welcome {.unnumbered}

```{r echo=FALSE}

# This page serves as the landing page for the web version of the book.

today <- Sys.Date()

```

Welcome to the Transdiagnostic Addiction Laboratory at Dalhousie University - we are glad to have you!

This is the comprehensive guide for students and trainees working within the Transdiagnostic Addiction Laboratory at Dalhousie University. Dalhousie University is located in Mi'kma'ki, the ancestral and unceded territory of the Mi'kmaq. We are all Treaty people.

The goal of this document is to provide you with a detailed guide on navigating programs at the University, as well as providing you with the general rules and expectations you should follow while working in the lab. We also provide some resources both for the program and for setting up and conducting research.

This document was inspired by several other documents (see [here](https://rennisonlab.com/lab-manual/) and [here](https://neurocognitive-imaging-lab.gitbook.io/ncil-lab-handbook/4KX9BrRxON7flu3dJyRM/start-here/introduction-to-ncil)) and is a work in progress. If you have feedback and/or suggested updates, please reach out to the lab manager at {{< var emails.manager >}}.

