---
title: "Practica"
---

All students begin practicum training in the Winter and Spring terms of their first year through two course-based assessment practica (Child Assessment: PSYO 6107; and Adult Assessment: PSYO 6108). Following these course-based practica, all students will complete an internal assessment practicum at CPH (the program’s internal training clinic) during Summer term of first year. In the Winter term of the second year, all students complete a beginning intervention practicum (PSYO 6214) at CPH. Following this course-based practicum, all students will complete an intervention practicum at CPH during Spring/Summer and Fall terms of their second year and into their third year. This practicum may also include additional assessment experience.

All students must show satisfactory performance in their course-based practica and practica at CPH in order to begin external practicum training in assessment and/or intervention. Students who do not show satisfactory performance may be required to participate in additional practica at CPH (assessment and/or intervention). Students are also required to complete a supervision practicum at CPH following successful completion of PSYO 6303.

From third year and beyond, students complete community-based or external practica that will enable them to further develop their clinical skills by exposure to breadth and depth of experience in a variety of clinical settings. External practicum placements during the academic year are generally not allowed for first and second year students. Any student desiring an exception must obtain approval from the Field Placement Coordinator, Director of Clinical Training, and their Dissertation Supervisor.

Practica can be four, six, eight, or 12 months in duration. It is recommended that therapy focused placements be a minimum of six months. In order to gain the most from practicum training and ensure a broad range of experience, students will work closely with the Field Placement Coordinator (FPC) to determine overall training goals, a related sequence of training, and placements which will most appropriately meet their goals. Prior to initiating a practicum placement, the student shall discuss with the FPC the goals and objectives they are planning to work toward. The FPC will review the student's current level of competencies in courses and clinical experiences and recommend appropriate placements. Students may also use their own initiative, in consultation with the FPC, to find practicum sites that meet their interests and goals. Consideration must also be given to the scheduling of practicum hours vis-à-vis the student’s other academic requirements and the availability of practicum positions within the desired sites.

Students are required to keep the FPC informed regarding the pursuit of practicum placements prior to making arrangements or completing placement applications. Students should keep the FPC informed of any changes with placements (e.g., beginning/ending dates, supervisor changes). Students are also encouraged to consult with the FPC if any concerns or difficulties emerge during a practicum placement.

Students are expected to handle their practicum duties, including submitting necessary paperwork as well as tracking their hours as per department policies.

CPA recommends a total of 1000 practicum hours, including a minimum of 300 face-to-face intervention and assessment hours, be accrued during a students’ time in the program. However, more hours/practica experiences may be necessary to ensure a competitive residency application.

More details can be found in the [practicum guidelines document](guidelines.qmd).

## Summary

It is expected that students complete a total of approximately 1000 practicum hours during their time in the program. Students are encouraged to review the policy regarding internship readiness developed by the Canadian Council of Professional Psychology Programs (CCPPP) for additional guidance regarding appropriate numbers and types of practicum hours. The Program discourages excessive practicum hours as this generally slows progress and does not increase competitiveness for internship. For all external practica, students must obtain the approval of the field placement coordinator (FPC) AND the dissertation supervisor for each practicum placement. The dissertation supervisor’s approval is intended as a mechanism to ensure that the student is on track in all areas of their program. A student may appeal his or her supervisor’s decision to deny permission to progress with additional practicum hours through the director of clinical training (or designate). Practica are planned in conjunction with the FPC to ensure that a broad range of experience covering various forms of clinical practice are undertaken. All clinical students must register for PSYO 8333.06 (each term), each year they are in the Program prior to internship as this is the course through which practicum hours are tracked. As well, registration in this course will allow for students to be covered for liability insurance reasons. There will be no regularly scheduled classes for this course, but rather students may be asked to meet for specific reasons, which would be communicated to them in advance of the required meeting dates. Assuming all course requirements are met for PSYO 8333.06, a grade of PASS will be recorded for each student prior to internship. Prior to receiving a PASS, the student will be assigned a grade of IP (In Progress).
