---
title: "Designing your project"
---

This section is not meant to be an exhaustive guide on how to design your projects. Rather, the goal is to provide a few key considerations we believe are important in our lab.

## Survey-based designs

If you are designing a survey-based study, an important consideration is the use of attention checks and inconsistency checks (see @belliveau2022) integrated within the survey. Unfortunately, many participants in survey based research may not be providing genuine answers to our surveys (see @belliveau2022a). Within our lab, we seek to have the highest quality data possible. Part of this process is accomplished through the use of attention checks and inconsistency checks. We generally exclude participants who fail any given attention or inconsistency check in a survey. Additionally, these questions should be distributed evenly throughout the survey.

::: {.callout-note appearance="simple"}
## Once you have your survey created on REDCap or Qualtrics...

Before submitting your survey to Igor for review, you should first:

-   Compile a document of questionnaires with references and a table of contents

-   Ensure that all questions from the above document are present in the survey

-   Ensure that all variables needed for your hypotheses are present in the survey

-   Check spelling, grammar, and formatting

-   Check all branching logic with any answer possibilities

-   Avoid the use of unnecessary text-entry boxes (dropdown boxes or checkboxes are preferred)

-   Have peers in the lab conduct test runs through the survey and determine the average completion time. Does this align with what was estimated in your ethics application?
:::

### Attention checks

We use several types of attention checks. You should incorporate at least 1 of each type within your survey (for shorter survey designs, e.g. as part of a qualitative study, 1 or 2 attention checks in total are sufficient). The wording of these questions should be simple and straightforward; our goal is not to deceive participants, but rather catch those who are picking responses without reading the question prompts.

|                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|---------------------------|---------------------------------------------|
| Select-C-type                                                       | These types of questions instruct participants on which answer choice to select. Participants selecting any answer other than the instructed answer choice are considered inattentive.                                                                                                                                                                                                                                                       |
| Quiz-type                                                           | These questions quiz participants on instructions they should have read. Note that Dalhousie REB often requires this type of quiz with regards to evaluating informed consent for participants.                                                                                                                                                                                                                                              |
| [Honeypot](https://en.wikipedia.org/wiki/Honeypot_(computing))-type | These questions aim to minimize [desirability bias](https://en.wikipedia.org/wiki/Social-desirability_bias). These types of questions may, for example, ask participants if they completed some training program unrelated to the study and if so, provide participants with open-ended responses for feedback on this program. Any participants who indicate participating in the training and providing feedback are considered ingenuine. |

### Inconsistency checks

These types of questions should serve to double-check both [inclusion criteria]{.underline} and [key variables]{.underline} to the study. These questions can be formatted as simple repetitions (e.g., asking for participants' age twice at two points within the survey) or by evaluating variations of the same question (e.g., asking for participants' age at one point, and later asking for date of birth).

As many projects within our lab are on the topic of addiction, these questions can evaluate the behaviours or substances under examination. For example, if it's required that participants play video games at least once per week over 3 months, you may have this question in your screening questions:

> How often over the past 3 months have you played video games?
>
> -   Daily
>
> -   Every 2 to 3 days
>
> -   Once per week
>
> -   Less than once per week
>
> -   I have not played video games in the past 3 months

Here, the first 3 answer choices are considered eligible for the study. A follow-up question later in the study evaluating participants' gaming behaviour can be formatted as follows:

> Over the past 3 months, how long is your typical gaming session?
>
> -   \<1 hour
>
> -   1-3 hours
>
> -   3\< hours
>
> -   I have not played video games in the past 3 months

In this case, participants should never select the final answer choice. Any participants who do can be considered ineligible.

## Qualitative designs

### Designing interviews

### Designing behavioural observation studies
