---
title: "New to the lab? Start here"
---

Before you begin working in this lab, all members are expected to do the below.

## Read this manual {#sec-read-this-manual}

This manual contains all of the [policies and expectations](policies.qmd) you are expected to follow while working in the lab, and provides you with many [resources](resources.qmd) you may need throughout your research journey. Our goal with this document is to add in resources as they come up through working with students on different research projects.

It is good practice to consult this manual before asking Igor for assistance on a specific topic.

## Complete Ethics Training {#sec-complete-ethics-training}

As an incoming student in the lab, part of your on-boarding will be to complete the [TCPS 2: CORE Course on Research Ethics](https://tcps2core.ca/welcome). You will not be permitted to participate in research within the lab until you have completed this course and emailed proof of completion to the lab manager, {{< var names.manager >}} at {{< var emails.manager >}}.

## Get Access {#sec-get-access}

### Access to spaces

The Department requires that the hallway leading to the lab spaces remain locked 24/7. This door is only accessible by keycode associated with your DalCard. The lab manager will need to set up this access for you.

Before you can enter, even if you have been granted access by the Department, you will need a PIN code associated with your DalCard. If you lived in a residence or otherwise have had access to an area on campus that required you tap your DalCard and input a PIN, this door will use the same PIN. Otherwise, if you have not set up a PIN already, you can set one on the [DalCard website](https://www.dal.ca/campus_life/Dalcard/your-dalcard-account.html).

### Access to virtual resources

The project you are working on may have different demands as to what specific resources you need. You should familiarize yourself with the [software](https://libraries.dal.ca/help/software-downloads.html) available to you through Dalhousie. Additionally, the majority of lab communication is carried out through [Slack](https://slack.com/). If you haven't received an invitation, please let the lab manager {{< var names.manager >}} know. If you are working on a systematic review, you will likely need an account created in [Covidence](https://dal.ca.libguides.com/systematicreviews/CovidenceHelp). Students enrolled in the lab will need to get access to OneDrive, where all research files relating to the lab are stored. Otherwise, the specific demands of the project will be communicated to you.

#### Social media

The lab has several social media accounts (Twitter/X, Reddit, Kijiji, and Instagram) which are available for use by students in the lab upon request. If you would like to make use of these accounts for your research projects and you have approval from {{< var names.pi >}}, please ask the lab manager {{< var names.manager >}} for access. These can be used to post your own recruitment advertisements, or to reach out to other social media pages for sharing your recruitment materials.

## Lab Website

All lab members are encouraged to submit a semi-professional headshot and short biography to be posted on our [lab website](https://www.talab.ca). This information allows us to showcase our lab members, and also allows you to have some proof of engagement with the lab beyond your CV entry. You can view some example biographies on the lab website. In general, these should give a brief description of yourself both professionally and personally, as well as your research interests. The photographs must be taken in landscape format and should not be blurry. You can also provide social media links which can be linked alongside your bio. Once you have this information, please forward it to {{< var emails.manager >}} to be posted on the lab drive.

## Review the Below {#sec-review-the-below}

Depending on whether you are an incoming [Volunteer](volunteer.qmd), [Honours or (In)dependent project student](undergrad.qmd), or [Graduate student](graduate.qmd), you may have further steps you should consider. Please consult the relevant sections.
